name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - {rosdistro: 'noetic', container: 'ros:noetic-ros-base-focal'}
    container: ${{ matrix.config.container }}
    
    steps:        
    - name: update git
      run: |
        apt update 
        apt install -y software-properties-common
        add-apt-repository ppa:git-core/ppa
        apt update
        apt install -y git

    - name: Clone repo with submodules
      run: |
        git clone --recursive https://github.com/${{ github.repository }} .
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        
    - name: Install catkin-tools on Noetic
      run: |
        apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
        apt update
        apt install -y python3-pip
        pip3 install osrf-pycommon
        apt update
        apt install -y python3-wstool python3-catkin-tools
        
    - name: release_build_test
      working-directory: ${{ github.workspace }}
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        apt update
        apt install -y python3-wstool autoconf libtool
        catkin init
        catkin config --extend "/opt/ros/${{matrix.config.rosdistro}}"
        catkin config --merge-devel
        
    - name: install Gazebo
      working-directory: ${{ github.workspace }}
      run: |
        chmod +x scripts/install_gazebo.sh
        ./scripts/install_gazebo.sh

    - name: install MAVROS
      working-directory: ${{ github.workspace }}
      run: |
        chmod +x scripts/install_mavros.sh
        ./scripts/install_mavros.sh

    - name: prepare EasonDrone
      working-directory: ${{ github.workspace }}
      run: |
        apt update
        apt install -y cmake
        apt install -y libgoogle-glog-dev libgflags-dev
        apt install -y libatlas-base-dev
        apt install -y libeigen3-dev
        apt install -y libsuitesparse-dev
        apt install -y ros-noetic-velodyne*
        apt install -y ros-noetic-usb-cam
        apt install -y ros-noetic-vision-msgs
        pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        pip3 install tqdm seaborn
        apt install -y ros-noetic-move-base
        apt install -y ros-noetic-moveit
        apt install -y libarmadillo-dev
        apt install -y ros-noetic-tf2*
        apt install -y ros-noetic-octomap* octovis
        apt install -y libzmqpp-dev

    - name: install ceres-solver
      working-directory: ${{ github.workspace }}
      run: |
        cd 3rdparty/ceres-solver
        mkdir build && cd build
        cmake ..
        make
        make install

    - name: install Livox-SDK
      working-directory: ${{ github.workspace }}
      run: |
        cd src/lidar/Livox-SDK
        mkdir build && cd build
        cmake ..
        make
        make install

    - name: install Livox-SDK2
      working-directory: ${{ github.workspace }}
      run: |
        cd src/lidar/Livox-SDK2
        mkdir build && cd build
        cmake ..
        make
        make install

    - name: install Sophus
      working-directory: ${{ github.workspace }}
      run: |
        cd 3rdparty/Sophus
        mkdir build && cd build
        cmake ..
        make
        make install

    - name: install acados
      working-directory: ${{ github.workspace }}
      run: |
        cd 3rdparty/acados
        pip3 install -e interfaces/acados_template
        mkdir build && cd build
        cmake ..
        make
        make install
        echo "export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:~/easondrone_ws/3rdparty/acados/lib" >> ~/.bashrc
        echo "export ACADOS_SOURCE_DIR=~/easondrone_ws/3rdparty/acados" >> ~/.bashrc

    - name: install ArUco
      working-directory: ${{ github.workspace }}
      run: |
        cd 3rdparty/ArUco
        mkdir build && cd build
        cmake .. -DUSE_OWN_EIGEN3=OFF
        make
        make install

    - name: install nlopt
      working-directory: ${{ github.workspace }}
      run: |
        cd 3rdparty/nlopt
        mkdir build && cd build
        cmake ..
        make
        make install
        
    - name: catkin_make_isolated
      working-directory: ${{ github.workspace }}
      run: |
        catkin_make_isolated --ignore-pkg ceres-solver pangolin
        echo "source ~/easondrone_ws/devel_isolated/setup.bash" >> ~/.bashrc
        
