name: Build Tests (Ubuntu 20.04 + ROS Noetic)
on:
  push:
    branches:
    - 'master'
  pull_request:
    branches:
    - '*'
  workflow_dispatch:
    inputs:
      tags:
        description: 'This does nothing'
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - {rosdistro: 'noetic', container: 'ros:noetic-ros-base-focal'}
    container: ${{ matrix.config.container }}
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        submodules: recursive
    - name: Install catkin-tools on Noetic
      if: ${{ matrix.config.container == 'ros:noetic-ros-base-focal' }}
      run: |
        apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
        apt update && apt install -y python3-pip
        pip3 install osrf-pycommon
        apt update && apt install -y python3-wstool python3-catkin-tools
    - name: release_build_test
      working-directory: ${{ github.workspace }}
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        apt update
        apt install -y python3-wstool autoconf libtool git
        catkin init
        catkin config --extend "/opt/ros/${{matrix.config.rosdistro}}"
        catkin config --merge-devel
        chmod +x scripts/install_*.sh
        ./scripts/install_gazebo.sh
        ./scripts/install_mavros.sh
        ./scripts/install_easondrone.sh
